### ISSUE TITLE
postponed todo list

### ISSUE THREAD

**Issue by bthaile** [bthaile/compliance#1]
### Feature Upgrade List

- [ ] **User Management**
  - [ ] Get LenderId's from this endpoint: `compliance/lenders`
    ```json
    {"id":"549300FGXN1K3HLB1R50","name":"ROCKET MORTGAGE", "state":"TX", "city":"Austin", "fullName":"ROCKET MORTGAGE [Austin, TX]"}
    ```
  - [ ] Add an option to set the Lender for each user. Store the LenderId with the User's data.
  - [ ] When showing the Lender name in the dropdown, include the state and city (the fullName field).

- [ ] **Assess Areas**
  - [ ] Get the assessment areas from the endpoint and ensure they change based on the User's Lender Id.

- [ ] **Peer Group**
  - [ ] For Austin, TX:
    - [x] Increase the vertical height of the chart.
    - [ ] Some rows are missing since there are lots of rows.
    - [ ] Banks with longer names are cut on the left label. That is ok. Can we make the hover-over show the full name?
  - [x] Rename:
    - [x] `Type` --> `Loan Type`

- [ ] **Fair Lending Rank**
  - [ ] Instead of showing the percentage as a number at the end of the bar, show the "pct" and the "count".
    - Erik to add a new label field to the return JSON - use that instead of calculating the value.
  - [x] Rename:
    - [x] `Type` --> `Loan Type`

- [x] **Lending Trends**
  - [x] Rename:
    - [x] `Asset Type` --> `Loan Type`
    - [x] `Asset Area` --> `Assess Area`

- [ ] **Census Tracts**
  - [ ] User can sort on Total Originations and specify to see only rows for specific types: LMI, Minority, etc. tracts.
  - [ ] Fill in the missing data values.

- [ ] **Loan Portfolio**
  - [ ] Interest Rate label shows different than the other fields.
  - [ ] Get rows to display.

- [x] **Page Loading**
  - [x] When moving to a new dashboard/page, don't do an initial data load. Let the user enter their criteria and click Apply before loading data.

### Postpone to Next Version

- [ ] **Census Tracts**
  - [ ] Plot Census Tracts to map.

- [ ] **Loan Portfolio**
  - [ ] Plot to map.
